### ISSUE TITLE
Optical flow accuracy and calibration file；

### ISSUE THREAD

**Issue by xji-apex** [vbrebion/rt_of_low_high_res_event_cameras#4] opened 2022-05-22 08:59 UTC
Hello， I'm here again.
I use the public dataset([shapes_6dof](https://rpg.ifi.uzh.ch/davis_data.html) ) to test the OF accuracy.  I meet two questions:

1. The data structure of optical_flow is "32FC2", Does the numerical value on each pixel mean the optical flow velocity or the relative increment of the pixel displacement at the next frame？ What is the unit of the value?

2. I added the camera calibration file（as followed）
`%YAML:1.0
---
imageWidth: 240
imageHeight: 180
camera_matrix: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data:
    [  1.9909236654231120e+02,
      0.,
      1.3219207137770019e+02,
      0.,
      1.9882882047008860e+02,
      1.1071266001129560e+02,
      0.,
      0.,
      1.,
    ]
distortion_coefficients: !!opencv-matrix
  rows: 5
  cols: 1
  dt: d
  data:
    [
      -3.6843631179778730e-01,
      1.5094724355665831e-01,
      -2.9613053438486462e-04,
      -7.5943172624103202e-04,
      0.,
    ]`
But there were some problems：
![image](https://user-images.githubusercontent.com/71243343/169686195-c1b33346-10e5-496f-aef0-549a7d62b681.png)
When I canceled the calibration file, it looked normal：
![image](https://user-images.githubusercontent.com/71243343/169686354-a8f3831d-cc27-4a91-a957-ea7f9e4a2400.png)

Looking forward to your reply！
Thanks a ton！

**Comment by vbrebion** [comment] 2022-05-23 13:46
Hi,

Thanks again for your interest in our method!

To answer your first question, the values of the returned optical flow matrix indicate the relative displacement of each pixel from one edge image to another. Their unit is in pixels.

As for your second remark, you are right, there was indeed an issue in how the undistortion matrix was initialized. Thanks to your comment, this has now been fixed (see commit <https://github.com/vbrebion/rt_of_low_high_res_event_cameras/commit/8cbf9bdc2c77da098ca2caaf9dc0912868be4455>).
I have tested it quickly on the shapes_6dof sequence as well as on some high definition recordings, and the undistortion is now applied as intended.

If you have any follow-up question, do not hesitate to post it here. Otherwise, I let you close this issue :)

Best,
Vincent

**Comment by xji-apex** [comment] 2022-05-24 08:56
Thank you for your timely reply and update!
Now the problem has been solved, but I find that the actual pixel displacement is twice or more than the predicted result.
It's a little worse than I expected. 
If you have some relevant suggestions for improvement, please grant instruction!
Thank you！

**Comment by vbrebion** [comment] 2022-05-24 12:20
This is indeed quite surprising.

In order to better pinpoint the origin of the issue:

- On which dataset do you conduct the evaluation? Does it contain a ground truth flow you compare against or do you use another metric?
- What length of accumulation window have you chosen (in ms)?
- What values have you set for the `gammas` and `smooth_iterations` parameters of the optical flow node? Setting inadequate parameters can lead to oversmoothed/underestimated flow, which could be your issue here

**Comment by xji-apex** [comment] 2022-05-25 05:45
Yeah,
- The dataset is the ([shapes_translation](https://rpg.ifi.uzh.ch/davis_data.html) ). I use the optical flow value of a corner to predict its pixel position and compare it with the actual pixel position of the corner at the next frame. The error between the two frames is nearly an order of magnitude.    For ten consecutive frames, the predicted values of corners are accumulated and compared with the actual relative change value of pixel displacement.  It is found that the actual pixel displacement is twice or more than the predicted result.It's a little worse than I expected.
- The accumulation window has been tested at 10,30,50(ms), the errors of these values are relatively large.
- The gammas and smooth_iterations parameters are the default.
The launch file is as followed:
```
<launch>
  <!-- Edges node -->
  <node name="edges" pkg="rt_of_low_high_res_event_cameras" type="edges_node_replay" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="input_file" type="string" value="/home/xji/data/events/shapes_translation.bag"/>

    <param name="topic" type="string" value="/dvs/events"/>

    <param name="accumulation_window" type="int" value="30"/>
    <param name="height" type="int" value="180"/>
    <param name="width" type="int" value="240"/>
    <param name="queues_size" type="int" value="1"/>  
    <param name="calibration_file" type="str" value="/home/xji/ros/vo_emvs/src/rt_of_low_high_res_event_cameras/calib/test.yml"/>
  </node>

  <!-- Denoising & filling node -->
  <node name="denoising_filling" pkg="rt_of_low_high_res_event_cameras" type="denoising_filling_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="use_gpu_version" type="bool" value="true"/>
    <param name="denoising_min_neighbours" type="int" value="1"/>
    <param name="filling_min_neighbours" type="int" value="4"/>
    <param name="queues_size" type="int" value="1"/>
  </node>

  <!-- Distance surface node -->
  <node name="distance_surface" pkg="rt_of_low_high_res_event_cameras" type="distance_surface_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="use_gpu_version" type="bool" value="true"/>
    <param name="distance_surface_formulation" type="string" value="exponential"/>
    <param name="queues_size" type="int" value="1"/>
  </node>

  <!-- Optical flow node -->
  <node name="optical_flow" pkg="rt_of_low_high_res_event_cameras" type="optical_flow_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="pyramidal_flow_levels" type="int" value="3"/>
    <param name="max_flow" type="double" value="15.0"/>
    <rosparam param="gammas">[50.0, 250.0, 500.0]</rosparam>
    <rosparam param="smooth_iterations">[50, 25, 5]</rosparam>
    <param name="queues_size" type="int" value="1"/>
  </node>

  <!-- Optical flow visualization node arrows -->
  <node name="optical_flow_viz" pkg="rt_of_low_high_res_event_cameras" type="optical_flow_viz_node" ns="rt_of_low_high_res_event_cameras" output="screen">
    <param name="visualization_method" type="string" value="colors"/>
    <param name="clip_flow" type="double" value="-1"/>
    <param name="queues_size" type="int" value="1"/>
  </node>

  <!-- Display -->
  <node name="image_view" pkg="rqt_image_view" type="rqt_image_view" args="/rt_of_low_high_res_event_cameras/optical_flow_viz"/>

</launch>

```
Thank you！

**Comment by vbrebion** [comment] 2022-05-25 12:09
Thank you for the details!

In order to compare my results with yours on the shapes_translation dataset, I compared the edges image generated at time `t`, with the edges image at time `t+1` compensated by the flow generated between `t` and `t+1`.

In most cases, the visual results seem good. Here is an example (with accumulation_window = 25ms):

- Edges at time `t`:
![edges_t](https://user-images.githubusercontent.com/61004974/170253244-4ffb1dec-66a6-40d9-807d-7c322f6a97c6.png)
- Edges at time `t+1`:
![edges_t+1](https://user-images.githubusercontent.com/61004974/170253349-c1ed98a5-e79f-4bbe-8232-a3d947fa3705.png)
- Edges at time `t+1`, flow-compensated:
![edges_t+1_flow_compensated](https://user-images.githubusercontent.com/61004974/170253442-4bf39dcd-de42-46ba-a182-3698f3a9dfe9.png)
- Edges at time `t` (blue) and at `t+1` flow-compensated (green):
![superimposed](https://user-images.githubusercontent.com/61004974/170255441-45a2eaa1-7d67-49c9-99f5-5a697a446809.png)

However, in some cases, I do agree with you that some large errors can appear.
From what I observe, they happen in majority when the camera starts moving with more speed, leading to too many events being integrated, creating blurry edge images, and thus leading to incorrect optical flow estimations (as shown in our article, Section IV.H.).
Testing with lower accumulation times (for instance 10ms), seems to provide better results for these parts of the recording.

It is difficult for me however to further analyze the disappointing results you currently obtain, as I am not sure I understand correctly your full evaluation procedure.
For that reason, if you have any code you can easily share so that I may reproduce your results on my side and dig into them, do not hesitate to send it to me (either as a GitHub repo, zip file, or by email, as you prefer).

Best,
Vincent

**Comment by xji-apex** [comment] 2022-05-26 12:32
I use the image_watch tool to check the corner position and the predicted optical flow value.  As you said, events have a great correlation with the camera moving. I'll test again if there are any questions. 
Thank you for your opening work and help!

**Closed as completed** 2024-11-29 08:52 UTC
